### ISSUE TITLE
Create Endpoint POST /exchange/:exchangeId

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/workflow-coordinator#2]
For details of what goes into this endpoint, see `Section 2: Wallet initiates the exchange`, of the DCC's Enhanced VC-API Flow document, linked to from Slide 7 of the Sign-and-verify refactoring plan.

**Comment by kayaelle** [comment]
@dmitrizagidulin @jchartrand ok to close this issue?

**Comment by jchartrand** [comment]
Yes.

**Comment by kayaelle** [comment]
Thanks!
