### ISSUE TITLE
Create Endpoint POST /exchange/:exchId/:txId#4

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/workflow-coordinator#3]
For details of what goes into this endpoint, see Section 3: Wallet continues the exchange, of the DCC's Enhanced VC-API Flow document, linked to from Slide 7 of the Sign-and-verify refactoring plan.

**Comment by kayaelle** [comment]
@dmitrizagidulin @jchartrand ok to close this issue?

**Comment by jchartrand** [comment]
@kayaelle Yes, ok with me.

**Comment by kayaelle** [comment]
Thanks!
